import type { BillRecord } from "@/types/bill";

/**
 * Hand-authored invoice history records for contract compliance audit.
 * Storyline for project-1: 20 records, mostly verified, 3 flagged for distinct
 * reasons (including the unapproved quarry supplier INV-55190 linking to dev-3),
 * and 1 pending intake verification.
 * For project-4: 5 software/service supplier invoices.
 * All fields are hand-authored; no verification calculations run at runtime.
 */
export const bills: BillRecord[] = [
  // =========================================================================
  // Project 1: Riverside Metro Extension (Construction Infrastructure)
  // =========================================================================
  {
    id: "bill-101",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7102",
    invoiceDate: "2026-06-04",
    supplierName: "Apex Steel Works Ltd",
    supplierTaxId: "27AAACA9901M1Z1",
    materialCategory: "Reinforcing steel (Fe500)",
    quantity: 85,
    unit: "MT",
    totalValue: 5100000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-06-04T09:15:00.000Z",
  },
  {
    id: "bill-102",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7215",
    invoiceDate: "2026-06-18",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Coarse aggregate (40mm)",
    quantity: 240,
    unit: "tonnes",
    totalValue: 360000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-06-18T11:40:00.000Z",
  },
  {
    id: "bill-103",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7330",
    invoiceDate: "2026-07-02",
    supplierName: "Birla ReadyMix Concrete Corp",
    supplierTaxId: "27BBBCC2211D1Z8",
    materialCategory: "Ready-mix concrete M40",
    quantity: 120,
    unit: "m³",
    totalValue: 840000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "K. Deshmukh (Pier 14 Gate)",
    scannedAt: "2026-07-02T07:30:00.000Z",
  },
  {
    id: "bill-104",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7488",
    invoiceDate: "2026-07-15",
    supplierName: "ElectroWorks Systems Ltd",
    supplierTaxId: "27EEFFG5544K1Z3",
    materialCategory: "Armoured copper power cables",
    quantity: 1400,
    unit: "meters",
    totalValue: 1260000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "A. Joshi (Substation Intake)",
    scannedAt: "2026-07-15T14:10:00.000Z",
  },
  {
    id: "bill-105",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7560",
    invoiceDate: "2026-07-28",
    supplierName: "Apex Steel Works Ltd",
    supplierTaxId: "27AAACA9901M1Z1",
    materialCategory: "Reinforcing steel (Fe500)",
    quantity: 95,
    unit: "MT",
    totalValue: 5700000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-07-28T10:05:00.000Z",
  },
  {
    id: "bill-106",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7712",
    invoiceDate: "2026-08-05",
    supplierName: "Apex Steel Works Ltd",
    supplierTaxId: "27AAACA9901M1Z1",
    materialCategory: "Reinforcing steel (Fe500)",
    quantity: 165,
    unit: "MT",
    totalValue: 9900000,
    status: "flagged",
    flagReason: "Delivered volume exceeds the authorized milestone quota by 45 metric tonnes without variation approval.",
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-08-05T13:20:00.000Z",
  },
  {
    id: "bill-107",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7840",
    invoiceDate: "2026-08-11",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Fine manufactured sand",
    quantity: 320,
    unit: "tonnes",
    totalValue: 576000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "K. Deshmukh (Pier 14 Gate)",
    scannedAt: "2026-08-11T08:45:00.000Z",
  },
  {
    id: "bill-108",
    projectId: "project-1",
    invoiceNumber: "INV-2026-7992",
    invoiceDate: "2026-08-19",
    supplierName: "Birla ReadyMix Concrete Corp",
    supplierTaxId: "27BBBCC2211D1Z8",
    materialCategory: "Ready-mix concrete M40",
    quantity: 180,
    unit: "m³",
    totalValue: 1260000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "K. Deshmukh (Pier 14 Gate)",
    scannedAt: "2026-08-19T06:50:00.000Z",
  },
  {
    id: "bill-109",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8055",
    invoiceDate: "2026-08-25",
    supplierName: "Tata Ductile Piping Systems",
    supplierTaxId: "27TTTPP8833B1Z6",
    materialCategory: "Ductile iron drainage pipes",
    quantity: 450,
    unit: "meters",
    totalValue: 900000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "A. Joshi (Substation Intake)",
    scannedAt: "2026-08-25T15:30:00.000Z",
  },
  {
    id: "bill-110",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8190",
    invoiceDate: "2026-08-30",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Coarse aggregate (20mm)",
    quantity: 210,
    unit: "tonnes",
    totalValue: 336000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-08-30T11:00:00.000Z",
  },
  {
    id: "bill-111",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8340",
    invoiceDate: "2026-09-02",
    supplierName: "Ultratech Cement Ltd",
    supplierTaxId: "27UUUCC4499P1Z2",
    materialCategory: "Ordinary Portland cement (OPC 53)",
    quantity: 600,
    unit: "bags",
    totalValue: 240000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-02T09:20:00.000Z",
  },
  {
    id: "bill-112",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8510",
    invoiceDate: "2026-09-05",
    supplierName: "Birla ReadyMix Concrete Corp",
    supplierTaxId: "27BBBCC2211D1Z8",
    materialCategory: "Ready-mix concrete M40",
    quantity: 140,
    unit: "m³",
    totalValue: 980000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "K. Deshmukh (Pier 14 Gate)",
    scannedAt: "2026-09-05T07:15:00.000Z",
  },
  {
    id: "bill-113",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8690",
    invoiceDate: "2026-09-08",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Graded coarse aggregate",
    quantity: 260,
    unit: "tonnes",
    totalValue: 416000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-08T10:45:00.000Z",
  },
  // The blocked invoice from Screen 1 (connects Screen 1 to Screen 2 and to Issue dev-3):
  {
    id: "bill-114",
    projectId: "project-1",
    invoiceNumber: "INV-55190",
    invoiceDate: "2026-09-10",
    supplierName: "Shree Balaji Minerals",
    supplierTaxId: "27XYZQ9988K1Z2",
    materialCategory: "Sub-base aggregate and sand",
    quantity: 420,
    unit: "tonnes",
    totalValue: 1420000,
    status: "flagged",
    flagReason: "Supplier is not registered on the approved contract vendor schedule.",
    linkedIssueId: "dev-3",
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-10T08:14:00.000Z",
  },
  {
    id: "bill-115",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8821",
    invoiceDate: "2026-09-10",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Graded coarse aggregate (40mm)",
    quantity: 300,
    unit: "tonnes",
    totalValue: 480000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "K. Deshmukh (Pier 14 Gate)",
    scannedAt: "2026-09-10T14:30:00.000Z",
  },
  // Second flagged invoice: billed to a different purchasing entity
  {
    id: "bill-116",
    projectId: "project-1",
    invoiceNumber: "INV-2026-8835",
    invoiceDate: "2026-09-11",
    supplierName: "Quarry Q-114 Minerals Ltd",
    supplierTaxId: "27ABCDE1234F1Z5",
    materialCategory: "Graded stone aggregate",
    quantity: 450,
    unit: "tonnes",
    totalValue: 890000,
    status: "flagged",
    flagReason: "Invoice registered to Apex Urban Developers Ltd rather than the awarded contract recipient.",
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-11T16:00:00.000Z",
  },
  {
    id: "bill-117",
    projectId: "project-1",
    invoiceNumber: "INV-2026-9042",
    invoiceDate: "2026-09-12",
    supplierName: "Apex Steel Works Ltd",
    supplierTaxId: "27AAACA9901M1Z1",
    materialCategory: "Reinforcing steel (Fe500)",
    quantity: 110,
    unit: "MT",
    totalValue: 6600000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-12T09:40:00.000Z",
  },
  {
    id: "bill-118",
    projectId: "project-1",
    invoiceNumber: "INV-2026-9118",
    invoiceDate: "2026-09-12",
    supplierName: "ElectroWorks Systems Ltd",
    supplierTaxId: "27EEFFG5544K1Z3",
    materialCategory: "Earthing conductors and accessories",
    quantity: 350,
    unit: "meters",
    totalValue: 245000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "A. Joshi (Substation Intake)",
    scannedAt: "2026-09-12T11:25:00.000Z",
  },
  {
    id: "bill-119",
    projectId: "project-1",
    invoiceNumber: "INV-2026-9204",
    invoiceDate: "2026-09-13",
    supplierName: "Ultratech Cement Ltd",
    supplierTaxId: "27UUUCC4499P1Z2",
    materialCategory: "Ordinary Portland cement (OPC 53)",
    quantity: 500,
    unit: "bags",
    totalValue: 200000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Ramesh Patel (Site Gate 1)",
    scannedAt: "2026-09-13T08:30:00.000Z",
  },
  // Pending invoice awaiting physical gate delivery and QA verification
  {
    id: "bill-120",
    projectId: "project-1",
    invoiceNumber: "INV-2026-9350",
    invoiceDate: "2026-09-13",
    supplierName: "Tata Ductile Piping Systems",
    supplierTaxId: "27TTTPP8833B1Z6",
    materialCategory: "High-pressure storm overflow joints",
    quantity: 60,
    unit: "units",
    totalValue: 450000,
    status: "pending",
    flagReason: "Awaiting physical arrival at site gate and weighbridge reconciliation.",
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "Pending dispatch intake",
    scannedAt: "2026-09-13T11:00:00.000Z",
  },

  // =========================================================================
  // Project 4: State Citizen Services Portal (Software / Services Contract)
  // =========================================================================
  {
    id: "bill-401",
    projectId: "project-4",
    invoiceNumber: "INV-SW-2026-01",
    invoiceDate: "2026-06-30",
    supplierName: "Bharat Cloud Infrastructure Ltd",
    supplierTaxId: "27BBBCC8811K1Z9",
    materialCategory: "Dedicated sovereign cloud hosting cluster",
    quantity: 1,
    unit: "month",
    totalValue: 1850000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "V. Saxena (Infrastructure Lead)",
    scannedAt: "2026-06-30T17:00:00.000Z",
  },
  {
    id: "bill-402",
    projectId: "project-4",
    invoiceNumber: "INV-SW-2026-02",
    invoiceDate: "2026-07-31",
    supplierName: "Bharat Cloud Infrastructure Ltd",
    supplierTaxId: "27BBBCC8811K1Z9",
    materialCategory: "Dedicated sovereign cloud hosting cluster",
    quantity: 1,
    unit: "month",
    totalValue: 1850000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "V. Saxena (Infrastructure Lead)",
    scannedAt: "2026-07-31T18:15:00.000Z",
  },
  {
    id: "bill-403",
    projectId: "project-4",
    invoiceNumber: "INV-SW-2026-03",
    invoiceDate: "2026-08-15",
    supplierName: "Aadhaar e-KYC Connect Private Ltd",
    supplierTaxId: "27AAACC3344M1Z5",
    materialCategory: "Statutory identity verification API bundle",
    quantity: 250000,
    unit: "transactions",
    totalValue: 750000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "S. Rao (Procurement Officer)",
    scannedAt: "2026-08-15T11:20:00.000Z",
  },
  {
    id: "bill-404",
    projectId: "project-4",
    invoiceNumber: "INV-SW-2026-04",
    invoiceDate: "2026-08-31",
    supplierName: "Bharat Cloud Infrastructure Ltd",
    supplierTaxId: "27BBBCC8811K1Z9",
    materialCategory: "Dedicated sovereign cloud hosting cluster",
    quantity: 1,
    unit: "month",
    totalValue: 1850000,
    status: "verified",
    flagReason: null,
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "V. Saxena (Infrastructure Lead)",
    scannedAt: "2026-08-31T17:45:00.000Z",
  },
  {
    id: "bill-405",
    projectId: "project-4",
    invoiceNumber: "INV-SW-2026-05",
    invoiceDate: "2026-09-08",
    supplierName: "Offshore CDN Solutions GmbH",
    supplierTaxId: "99DEU8833119A1Z",
    materialCategory: "Global edge acceleration content network",
    quantity: 1,
    unit: "quarter",
    totalValue: 920000,
    status: "flagged",
    flagReason: "Supplier data residency does not comply with domestic hosting requirement.",
    linkedIssueId: null,
    registrationVerified: true,
    scannedBy: "V. Saxena (Infrastructure Lead)",
    scannedAt: "2026-09-08T12:10:00.000Z",
  },
];
