import type { Commitment } from "@/types/commitment";

/**
 * ANUBANDH prototype addition — hand-authored commitments for project-1,
 * tied to real node ids from db/nodes.ts. Every field here is a fixed
 * display value; nothing is computed. See plan.md/update (1).md TASK 1.8.
 */
export const commitments: Commitment[] = [
  {
    id: "cm-1",
    projectId: "project-1",
    nodeId: "node-1-structure",
    label: "Reinforcement steel must be Fe500 grade",
    subject: "Reinforcement steel grade",
    predicate: "must be",
    promisedValue: "Fe500",
    sourceLabel: "Structural Design Drawing Rev C",
    sourceRef: "DWG-STR-014",
    actorContractorId: "contractor-1",
    criticality: "STRUCTURAL",
    toleranceBand: "NONE",
    expectedEvidence: ["LAB_CERTIFICATE", "WEIGHBRIDGE"],
  },
  {
    id: "cm-2",
    projectId: "project-1",
    nodeId: "node-1-foundation",
    label: "Fine aggregate must be sourced from Quarry Q-114",
    subject: "Fine aggregate source",
    predicate: "must be sourced from",
    promisedValue: "Quarry Q-114 (GSTIN 27ABCDE1234F1Z5)",
    sourceLabel: "Approved Vendor List v3",
    sourceRef: "AVL-2025-03",
    actorContractorId: "contractor-1",
    criticality: "STRUCTURAL",
    toleranceBand: "NONE",
    expectedEvidence: ["GST_IRN_QR", "EWAY_BILL", "WEIGHBRIDGE"],
  },
  {
    id: "cm-3",
    projectId: "project-1",
    nodeId: "node-1-electrical",
    label: "Electrical works must be performed by ElectroWorks",
    subject: "Electrical works subcontractor",
    predicate: "must be performed by",
    promisedValue: "ElectroWorks (approved subcontractor)",
    sourceLabel: "Subcontract Agreement SC-04",
    sourceRef: "SC-04",
    actorContractorId: "contractor-2",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GATE_CREDENTIAL", "ATTENDANCE"],
  },
  {
    id: "cm-4",
    projectId: "project-1",
    nodeId: "node-1-plumbing",
    label: "Exterior fixture finish must match RAL 7035 Light Grey",
    subject: "Exterior fixture finish colour",
    predicate: "must match",
    promisedValue: "RAL 7035 Light Grey",
    sourceLabel: "Finishes Schedule Rev A",
    sourceRef: "FIN-002",
    actorContractorId: "contractor-1",
    criticality: "COSMETIC",
    toleranceBand: "COSMETIC",
    expectedEvidence: ["SITE_PHOTO"],
  },
  {
    id: "cm-5",
    projectId: "project-1",
    nodeId: "node-1-structure",
    label: "Elevated structure concrete must be M40 grade",
    subject: "Concrete grade",
    predicate: "must be",
    promisedValue: "M40",
    sourceLabel: "Structural Design Drawing Rev C",
    sourceRef: "DWG-STR-014",
    actorContractorId: "contractor-1",
    criticality: "STRUCTURAL",
    toleranceBand: "TIGHT",
    expectedEvidence: ["LAB_CERTIFICATE"],
  },
  {
    id: "cm-6",
    projectId: "project-1",
    nodeId: "node-1-structure",
    label: "Welders on the pour must hold current certification",
    subject: "Welder certification",
    predicate: "must hold",
    promisedValue: "Valid IS 817 welder certificate",
    sourceLabel: "Site Safety Plan v2",
    sourceRef: "SSP-002",
    actorContractorId: "contractor-1",
    criticality: "SAFETY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GATE_CREDENTIAL"],
  },
  {
    id: "cm-7",
    projectId: "project-1",
    nodeId: "node-1-structure",
    label: "One cube test per 30cum of concrete poured",
    subject: "Cube test frequency",
    predicate: "must be taken every",
    promisedValue: "30 cubic metres poured",
    sourceLabel: "Quality Assurance Plan Rev B",
    sourceRef: "QAP-011",
    actorContractorId: "contractor-1",
    criticality: "STRUCTURAL",
    toleranceBand: "NONE",
    expectedEvidence: ["LAB_CERTIFICATE"],
  },
  {
    id: "cm-8",
    projectId: "project-1",
    nodeId: "node-1-electrical",
    label: "Only rostered, credentialed workers may attend site",
    subject: "Attendance roster compliance",
    predicate: "must match",
    promisedValue: "Approved subcontractor roster",
    sourceLabel: "Subcontract Agreement SC-04",
    sourceRef: "SC-04",
    actorContractorId: "contractor-2",
    criticality: "IDENTITY",
    toleranceBand: "LOOSE",
    expectedEvidence: ["ATTENDANCE", "GATE_CREDENTIAL"],
  },
  {
    id: "cm-9",
    projectId: "project-1",
    nodeId: "node-1-foundation",
    label: "Cranes must stay within the geofenced work zone",
    subject: "Equipment geofence",
    predicate: "must remain within",
    promisedValue: "Site work-zone boundary",
    sourceLabel: "Site Safety Plan v2",
    sourceRef: "SSP-002",
    actorContractorId: "contractor-1",
    criticality: "SAFETY",
    toleranceBand: "LOOSE",
    expectedEvidence: ["EQUIPMENT_GPS"],
  },
  {
    id: "cm-10",
    projectId: "project-1",
    nodeId: "node-1-root",
    label: "Progress billed must not exceed independently observed progress",
    subject: "Progress billing accuracy",
    predicate: "must not exceed",
    promisedValue: "Observed progress",
    sourceLabel: "Contract Payment Terms",
    sourceRef: "CPT-01",
    actorContractorId: "contractor-1",
    criticality: "FINANCIAL",
    toleranceBand: "TIGHT",
    expectedEvidence: ["BANK_PAYMENT"],
  },
  {
    id: "cm-11",
    projectId: "project-1",
    nodeId: "node-1-electrical",
    label: "Subcontractor payments must route to the approved bank account",
    subject: "Payment routing",
    predicate: "must route to",
    promisedValue: "ElectroWorks approved account",
    sourceLabel: "Subcontract Agreement SC-04",
    sourceRef: "SC-04",
    actorContractorId: "contractor-2",
    criticality: "FINANCIAL",
    toleranceBand: "TIGHT",
    expectedEvidence: ["BANK_PAYMENT"],
  },
  {
    id: "cm-12",
    projectId: "project-1",
    nodeId: "node-1-wiring",
    label: "Traction power wiring insulation must meet IS 7098 standard",
    subject: "Wiring insulation standard",
    predicate: "must meet",
    promisedValue: "IS 7098",
    sourceLabel: "Electrical Design Spec Rev A",
    sourceRef: "ELS-007",
    actorContractorId: "contractor-2",
    criticality: "SAFETY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["LAB_CERTIFICATE"],
  },
  {
    id: "cm-13",
    projectId: "project-1",
    nodeId: "node-1-plumbing",
    label: "Daily progress photo required for drainage works",
    subject: "Progress documentation",
    predicate: "must be submitted",
    promisedValue: "One geo-tagged photo per day",
    sourceLabel: "Site Reporting Guideline v1",
    sourceRef: "SRG-01",
    actorContractorId: "contractor-1",
    criticality: "COSMETIC",
    toleranceBand: "LOOSE",
    expectedEvidence: ["SITE_PHOTO"],
  },

  // ---- ANUBANDH addition (TASK 9) — project-4 (software contract) ----
  {
    id: "cm-14",
    projectId: "project-4",
    nodeId: "node-4-auth",
    label: "Auth module must be built by named lead architect Ananth Iyer",
    subject: "Key personnel — Lead Architect",
    predicate: "must be performed by",
    promisedValue: "Ananth Iyer",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT"],
  },
  {
    id: "cm-15",
    projectId: "project-4",
    nodeId: "node-4-auth",
    label: "Auth module must include named security lead Karthik Nair",
    subject: "Key personnel — Security Lead",
    predicate: "must be performed by",
    promisedValue: "Karthik Nair",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT"],
  },
  {
    id: "cm-16",
    projectId: "project-4",
    nodeId: "node-4-payments",
    label: "Payments module must be built by named backend lead Divya Rao",
    subject: "Key personnel — Backend Lead",
    predicate: "must be performed by",
    promisedValue: "Divya Rao",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT"],
  },
  {
    id: "cm-17",
    projectId: "project-4",
    nodeId: "node-4-payments",
    label: "Payments module must include named QA lead Sana Sheikh",
    subject: "Key personnel — QA Lead",
    predicate: "must be performed by",
    promisedValue: "Sana Sheikh",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT"],
  },
  {
    id: "cm-18",
    projectId: "project-4",
    nodeId: "node-4-deploy",
    label: "Deploy pipeline must be run by named DevOps lead Rohan Desai",
    subject: "Key personnel — DevOps Lead",
    predicate: "must be performed by",
    promisedValue: "Rohan Desai",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT", "GATE_CREDENTIAL"],
  },
  {
    id: "cm-19",
    projectId: "project-4",
    nodeId: "node-4-deploy",
    label: "Deploy pipeline must include named frontend lead Meenal Joshi",
    subject: "Key personnel — Frontend Lead",
    predicate: "must be performed by",
    promisedValue: "Meenal Joshi",
    sourceLabel: "Statement of Work Annex B",
    sourceRef: "SOW-ANNEX-B",
    actorContractorId: "contractor-3",
    criticality: "IDENTITY",
    toleranceBand: "TIGHT",
    expectedEvidence: ["GIT_COMMIT"],
  },
  {
    id: "cm-20",
    projectId: "project-4",
    nodeId: "node-4-deploy",
    label: "All data subprocessors must be hosted in India",
    subject: "Data residency",
    predicate: "must be hosted in",
    promisedValue: "India",
    sourceLabel: "Data Protection Schedule",
    sourceRef: "DPS-01",
    actorContractorId: "contractor-3",
    criticality: "STRUCTURAL",
    toleranceBand: "NONE",
    expectedEvidence: ["SBOM"],
  },
  {
    id: "cm-21",
    projectId: "project-4",
    nodeId: "node-4-deploy",
    label: "Production build must use only the approved package list",
    subject: "Approved package list",
    predicate: "must match",
    promisedValue: "Approved Package List v4.2",
    sourceLabel: "Approved Package List v4.2",
    sourceRef: "APL-4.2",
    actorContractorId: "contractor-3",
    criticality: "STRUCTURAL",
    toleranceBand: "LOOSE",
    expectedEvidence: ["SBOM"],
  },
];
