import type { Deviation } from "@/types/deviation";

/**
 * ANUBANDH prototype addition — hand-authored deviations for project-1.
 * Every level, priority, timeRemaining and priorityFactors entry here is a
 * fixed display value; nothing is computed at runtime. The 14 `dev-f-*`
 * records are the small finish-related deviations rolled up into the
 * PROMOTED case (dev-6) via contributingDeviationIds. See
 * plan.md/update (1).md TASK 1.12.
 */
export const deviations: Deviation[] = [
  // --- L0/L1 cosmetic paint pair ---
  {
    id: "dev-1",
    projectId: "project-1",
    commitmentId: "cm-4",
    observationId: "obs-8",
    expectationId: "exp-4",
    kind: "MISMATCH",
    level: "L0",
    title: "Exterior fixture shade slightly off spec",
    promisedText: "RAL 7035 Light Grey",
    observedText: "Photo reads closer to RAL 7037 Dusty Grey",
    reasons: ["Cosmetic tolerance band — informational only"],
    valueAtRisk: 40_000,
    priority: 4.1,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (COSMETIC)", value: "x0.2" },
      { label: "Magnitude", value: "x0.5" },
      { label: "Value at risk", value: "Rs 40,000" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-05T11:00:00.000Z",
  },
  {
    id: "dev-2",
    projectId: "project-1",
    commitmentId: "cm-13",
    observationId: "obs-10",
    expectationId: "exp-13",
    kind: "MISMATCH",
    level: "L1",
    title: "Daily drainage photo submitted a day late",
    promisedText: "One geo-tagged photo per day",
    observedText: "Photo for day 13 arrived with day 14's batch",
    reasons: ["Minor reporting delay", "No safety or cost impact"],
    valueAtRisk: 0,
    priority: 6.5,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (COSMETIC)", value: "x0.2" },
      { label: "Magnitude", value: "x1.0" },
      { label: "Value at risk", value: "Rs 0" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2026-09-12T09:30:00.000Z",
  },

  // --- L3 material-source mismatch (the demo HOLD case) ---
  {
    id: "dev-3",
    projectId: "project-1",
    commitmentId: "cm-2",
    observationId: "obs-1",
    expectationId: "exp-2",
    kind: "MISMATCH",
    level: "L3",
    title: "Aggregate delivered from unapproved quarry (wrong GSTIN)",
    promisedText: "Quarry Q-114, GSTIN 27ABCDE1234F1Z5",
    observedText: "Shree Balaji Minerals, GSTIN 27XYZQ9988K1Z2 — not on approved vendor list",
    reasons: [
      "Seller GSTIN on the e-invoice does not match the approved vendor list",
      "E-way bill origin is 40km from the approved quarry",
      "Bank payment settled to the unapproved seller, not Quarry Q-114",
      "Feeds directly into the structural concrete pour scheduled today",
    ],
    valueAtRisk: 14_200_000,
    priority: 91.4,
    timeRemaining: "3h 49m",
    priorityFactors: [
      { label: "Criticality (STRUCTURAL)", value: "x4.0" },
      { label: "Magnitude", value: "x1.0" },
      { label: "Value at risk", value: "Rs 1.42 Cr" },
      { label: "Recurrence", value: "x1.2" },
      { label: "Time remaining", value: "÷ 3.8 hours" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-12T08:11:00.000Z",
  },

  // --- L4 identity case ---
  {
    id: "dev-4",
    projectId: "project-1",
    commitmentId: "cm-3",
    observationId: "obs-5",
    expectationId: "exp-3",
    kind: "MISMATCH",
    level: "L4",
    title: "Unapproved subcontractor crew on site (revoked credential)",
    promisedText: "ElectroWorks (approved subcontractor)",
    observedText: "6 workers badged in under 'Rapid Electricals' — credential REVOKED",
    reasons: [
      "Gate credential belongs to a subcontractor with a REVOKED credential",
      "None of the 6 biometric check-ins match the ElectroWorks roster",
      "Site photo shows unbadged crew working on a live electrical panel",
    ],
    valueAtRisk: 6_800_000,
    priority: 88.7,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (IDENTITY)", value: "x3.5" },
      { label: "Magnitude", value: "x1.0" },
      { label: "Value at risk", value: "Rs 68,00,000" },
      { label: "Recurrence", value: "x1.0" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "EVIDENCE_REQUESTED",
    raisedAt: "2026-09-11T07:15:00.000Z",
  },

  // --- SILENCE case: missing lab certificate ---
  {
    id: "dev-5",
    projectId: "project-1",
    commitmentId: "cm-7",
    observationId: null,
    expectationId: "exp-6",
    kind: "SILENCE",
    level: "L3",
    title: "Cube test certificate never arrived for pour batch 22",
    promisedText: "One cube test certificate per 30cum poured",
    observedText: "",
    reasons: [
      "Delivery records show enough concrete for a batch-22 cube test",
      "No lab certificate has been filed for batch 22",
      "6 days past the 28-day testing window",
    ],
    valueAtRisk: 3_100_000,
    priority: 52.3,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (STRUCTURAL)", value: "x4.0" },
      { label: "Magnitude", value: "x0.6" },
      { label: "Value at risk", value: "Rs 31,00,000" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-12T00:00:00.000Z",
  },

  // --- PROMOTED L2 case: systematic finish downgrade ---
  {
    id: "dev-6",
    projectId: "project-1",
    commitmentId: "cm-4",
    observationId: null,
    expectationId: null,
    kind: "PROMOTED",
    level: "L2",
    title: "Systematic finish downgrade (14 items, Rs 18.2L)",
    promisedText: "RAL 7035 Light Grey across all exterior fixtures",
    observedText: "14 separate off-spec finish items, individually filed as cosmetic",
    reasons: [
      "14 individually-harmless finish deviations share the same off-spec pattern",
      "Read together, they represent a systematic downgrade rather than isolated mistakes",
      "Cumulative value at risk crosses the material threshold even though each item is cosmetic",
    ],
    valueAtRisk: 1_820_000,
    priority: 61.0,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (COSMETIC x14, promoted)", value: "x1.5" },
      { label: "Magnitude (cumulative)", value: "x1.0" },
      { label: "Cumulative value at risk", value: "Rs 18,20,000" },
    ],
    contributingDeviationIds: [
      "dev-f-1", "dev-f-2", "dev-f-3", "dev-f-4", "dev-f-5", "dev-f-6", "dev-f-7",
      "dev-f-8", "dev-f-9", "dev-f-10", "dev-f-11", "dev-f-12", "dev-f-13", "dev-f-14",
    ],
    cumulativeValue: 1_820_000,
    status: "OPEN",
    raisedAt: "2026-09-12T12:00:00.000Z",
  },

  // --- remaining standalone deviations, rounding out the demo set ---
  {
    id: "dev-7",
    projectId: "project-1",
    commitmentId: "cm-9",
    observationId: "obs-16",
    expectationId: "exp-9",
    kind: "MISMATCH",
    level: "L2",
    title: "Tower crane operated outside the geofenced work zone",
    promisedText: "Crane must remain within the site work-zone boundary",
    observedText: "Crane TC-02 operated 40m outside the geofence for 12 minutes",
    reasons: ["GPS telemetry shows a geofence breach", "No incident reported by site safety officer"],
    valueAtRisk: 0,
    priority: 34.2,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (SAFETY)", value: "x2.5" },
      { label: "Magnitude", value: "x0.5" },
      { label: "Value at risk", value: "Rs 0" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2026-09-08T16:00:00.000Z",
  },
  {
    id: "dev-8",
    projectId: "project-1",
    commitmentId: "cm-8",
    observationId: "obs-15",
    expectationId: null,
    kind: "MISMATCH",
    level: "L1",
    title: "One ElectroWorks worker missing from daily roster",
    promisedText: "Full approved roster present",
    observedText: "11 of 12 rostered workers checked in",
    reasons: ["Single absence, flagged for reconciliation only"],
    valueAtRisk: 0,
    priority: 12.0,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (IDENTITY)", value: "x0.4" },
      { label: "Magnitude", value: "x0.3" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2026-09-09T07:30:00.000Z",
  },
  {
    id: "dev-9",
    projectId: "project-1",
    commitmentId: "cm-11",
    observationId: "obs-19",
    expectationId: "exp-11",
    kind: "MISMATCH",
    level: "L3",
    title: "Subcontractor payment routed to an unlisted bank account",
    promisedText: "ElectroWorks approved account",
    observedText: "Rs 2,40,000 paid to an account not on the approved subcontractor list",
    reasons: [
      "Bank settlement record shows a different account number than SC-04's approved list",
      "No payment-routing confirmation was ever filed",
    ],
    valueAtRisk: 240_000,
    priority: 58.9,
    timeRemaining: "6h 02m",
    priorityFactors: [
      { label: "Criticality (FINANCIAL)", value: "x3.0" },
      { label: "Magnitude", value: "x1.0" },
      { label: "Value at risk", value: "Rs 2,40,000" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-11T09:00:00.000Z",
  },
  {
    id: "dev-10",
    projectId: "project-1",
    commitmentId: "cm-2",
    observationId: "obs-3",
    expectationId: null,
    kind: "MISMATCH",
    level: "L0",
    title: "Weighbridge tonnage 0.6t under the delivery note",
    promisedText: "19.0 tonnes per delivery note",
    observedText: "18.4 tonnes recorded at the weighbridge",
    reasons: ["Within normal weighing tolerance"],
    valueAtRisk: 0,
    priority: 3.0,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (STRUCTURAL)", value: "x0.1" },
      { label: "Magnitude", value: "x0.2" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2026-09-10T08:25:00.000Z",
  },
  {
    id: "dev-11",
    projectId: "project-1",
    commitmentId: "cm-12",
    observationId: null,
    expectationId: "exp-12",
    kind: "MISMATCH",
    level: "L1",
    title: "Wiring insulation certificate filed 2 days late",
    promisedText: "Certificate within 14 days of installation",
    observedText: "Filed on day 16",
    reasons: ["Late filing only, test result itself passed"],
    valueAtRisk: 0,
    priority: 9.5,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (SAFETY)", value: "x0.5" },
      { label: "Magnitude", value: "x0.3" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2025-09-26T00:00:00.000Z",
  },
  {
    id: "dev-12",
    projectId: "project-1",
    commitmentId: "cm-10",
    observationId: null,
    expectationId: "exp-10",
    kind: "MISMATCH",
    level: "L2",
    title: "Billed progress 8 points ahead of independently observed progress",
    promisedText: "Billed progress must not exceed observed progress",
    observedText: "Billed 53%, observed progress 45%",
    reasons: ["Progress claim not yet reconciled against gate/weighbridge/photo evidence"],
    valueAtRisk: 4_000_000,
    priority: 41.6,
    timeRemaining: "1d 4h",
    priorityFactors: [
      { label: "Criticality (FINANCIAL)", value: "x3.0" },
      { label: "Magnitude", value: "x0.6" },
      { label: "Value at risk", value: "Rs 40,00,000" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-12T06:00:00.000Z",
  },

  // --- ANUBANDH addition (TASK 9) — project-4 (software contract) ---
  {
    id: "dev-13",
    projectId: "project-4",
    commitmentId: "cm-21",
    observationId: "obs-26",
    expectationId: null,
    kind: "MISMATCH",
    level: "L0",
    title: "Patch-version dependency bump (4.2.1 to 4.2.3)",
    promisedText: "Approved Package List v4.2, pinned versions",
    observedText: "Dependency running v4.2.3, a patch-only bump",
    reasons: ["Patch-level change only, no functional or security-relevant diff"],
    valueAtRisk: 0,
    priority: 3.5,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (STRUCTURAL, LOOSE tolerance)", value: "x0.2" },
      { label: "Magnitude", value: "x0.2" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "CLOSED",
    raisedAt: "2026-08-30T09:00:00.000Z",
  },
  {
    id: "dev-14",
    projectId: "project-4",
    commitmentId: "cm-20",
    observationId: "obs-27",
    expectationId: null,
    kind: "MISMATCH",
    level: "L3",
    title: "New data subprocessor hosted outside India",
    promisedText: "All subprocessors hosted in India",
    observedText: "CloudRegion-EU-West subprocessor added in release 4.3.0's SBOM",
    reasons: [
      "SBOM for release 4.3.0 lists a subprocessor with no India hosting region",
      "Data-residency commitment has zero tolerance for this",
      "Feeds directly into today's production deploy",
    ],
    valueAtRisk: 9_500_000,
    priority: 84.0,
    timeRemaining: "5h 00m",
    priorityFactors: [
      { label: "Criticality (STRUCTURAL)", value: "x4.0" },
      { label: "Magnitude", value: "x1.0" },
      { label: "Value at risk", value: "Rs 95,00,000" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "OPEN",
    raisedAt: "2026-09-11T22:05:00.000Z",
  },
  {
    id: "dev-15",
    projectId: "project-4",
    commitmentId: "cm-18",
    observationId: "obs-28",
    expectationId: null,
    kind: "MISMATCH",
    level: "L4",
    title: "71% of recent commits from an uncredentialed contributor",
    promisedText: "Named senior personnel (Ananth Iyer, Karthik Nair, Divya Rao, Sana Sheikh, Rohan Desai, Meenal Joshi) perform the work",
    observedText: "71% of commits from Deepak Shah (credential REVOKED); 4 of 6 named seniors at zero commits",
    reasons: [
      "Commit history shows the bulk of recent work done by someone with no active credential",
      "Four of the six contractually-named senior personnel show zero commits in 30 days",
      "Key-personnel commitment appears to exist on paper only",
    ],
    valueAtRisk: 12_000_000,
    priority: 92.1,
    timeRemaining: "passed",
    priorityFactors: [
      { label: "Criticality (IDENTITY)", value: "x3.5" },
      { label: "Magnitude", value: "x1.2" },
      { label: "Value at risk", value: "Rs 1.2 Cr" },
    ],
    contributingDeviationIds: [],
    cumulativeValue: null,
    status: "EVIDENCE_REQUESTED",
    raisedAt: "2026-09-12T00:10:00.000Z",
  },

  // --- 14 small finish deviations contributing to dev-6 (PROMOTED) ---
  ...Array.from({ length: 14 }, (_, i) => {
    const n = i + 1;
    const spots = [
      "Block A staircase railing", "Block A entrance canopy", "Block B staircase railing",
      "Block B entrance canopy", "Platform 1 bench frames", "Platform 1 signage frames",
      "Platform 2 bench frames", "Platform 2 signage frames", "Concourse handrail",
      "Concourse ticket booth trim", "Lift lobby door frame", "Lift lobby skirting",
      "Station facade fascia panel", "Station facade drainage spout",
    ][i];
    return {
      id: `dev-f-${n}`,
      projectId: "project-1",
      commitmentId: "cm-4",
      observationId: n % 2 === 0 ? "obs-9" : "obs-8",
      expectationId: "exp-4",
      kind: "MISMATCH" as const,
      level: (n % 3 === 0 ? "L1" : "L0") as "L0" | "L1",
      title: `Finish shade deviation — ${spots}`,
      promisedText: "RAL 7035 Light Grey",
      observedText: "Photo reads closer to RAL 7037 Dusty Grey",
      reasons: ["Cosmetic tolerance band — filed individually as informational"],
      valueAtRisk: 130_000,
      priority: 4.0 + n * 0.1,
      timeRemaining: "passed",
      priorityFactors: [
        { label: "Criticality (COSMETIC)", value: "x0.2" },
        { label: "Value at risk", value: "Rs 1,30,000" },
      ],
      contributingDeviationIds: [],
      cumulativeValue: null,
      status: "OPEN" as const,
      raisedAt: "2026-09-0" + ((n % 9) + 1) + "T10:00:00.000Z",
    };
  }),
];
