import type { Expectation } from "@/types/observation";

/**
 * ANUBANDH prototype addition — one expectation per piece of evidence a
 * commitment in db/commitments.ts said should eventually arrive. Mostly
 * MET, with two MISSING (one of which is the LAB_CERTIFICATE that feeds the
 * SILENCE deviation). See plan.md/update (1).md TASK 1.11.
 */
export const expectations: Expectation[] = [
  {
    id: "exp-1",
    commitmentId: "cm-1",
    expectedType: "LAB_CERTIFICATE",
    expectedLabel: "Reinforcement steel batch certificate",
    dueLabel: "Within 7 days of delivery",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-2",
    commitmentId: "cm-2",
    expectedType: "GST_IRN_QR",
    expectedLabel: "GST e-invoice for aggregate delivery",
    dueLabel: "At time of delivery",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-3",
    commitmentId: "cm-3",
    expectedType: "GATE_CREDENTIAL",
    expectedLabel: "Valid gate credential for subcontractor crew",
    dueLabel: "At time of site entry",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-4",
    commitmentId: "cm-4",
    expectedType: "SITE_PHOTO",
    expectedLabel: "Fixture finish photo",
    dueLabel: "Within 3 days of painting",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-5",
    commitmentId: "cm-5",
    expectedType: "LAB_CERTIFICATE",
    expectedLabel: "M40 concrete cube test certificate",
    dueLabel: "Within 28 days of pour",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-6",
    commitmentId: "cm-7",
    expectedType: "LAB_CERTIFICATE",
    expectedLabel: "Cube test certificate for pour batch 22",
    dueLabel: "Within 28 days of pour (due 2026-09-06)",
    overdueLabel: "6 days overdue",
    status: "MISSING",
  },
  {
    id: "exp-7",
    commitmentId: "cm-6",
    expectedType: "GATE_CREDENTIAL",
    expectedLabel: "Welder IS 817 certification scan",
    dueLabel: "At time of site entry",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-8",
    commitmentId: "cm-8",
    expectedType: "ATTENDANCE",
    expectedLabel: "Daily roster reconciliation",
    dueLabel: "Daily",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-9",
    commitmentId: "cm-9",
    expectedType: "EQUIPMENT_GPS",
    expectedLabel: "Crane geofence telemetry",
    dueLabel: "Continuous, reviewed weekly",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-10",
    commitmentId: "cm-10",
    expectedType: "BANK_PAYMENT",
    expectedLabel: "Progress billing reconciliation",
    dueLabel: "Monthly",
    overdueLabel: null,
    status: "PENDING",
  },
  {
    id: "exp-11",
    commitmentId: "cm-11",
    expectedType: "BANK_PAYMENT",
    expectedLabel: "Payment routing confirmation",
    dueLabel: "Within 2 days of payment (due 2026-09-13)",
    overdueLabel: "2 days overdue",
    status: "MISSING",
  },
  {
    id: "exp-12",
    commitmentId: "cm-12",
    expectedType: "LAB_CERTIFICATE",
    expectedLabel: "Wiring insulation test certificate",
    dueLabel: "Within 14 days of installation",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-13",
    commitmentId: "cm-13",
    expectedType: "SITE_PHOTO",
    expectedLabel: "Daily drainage progress photo",
    dueLabel: "Daily",
    overdueLabel: null,
    status: "PENDING",
  },

  // ---- ANUBANDH addition (TASK 9) — project-4 ----
  {
    id: "exp-14",
    commitmentId: "cm-14",
    expectedType: "GIT_COMMIT",
    expectedLabel: "Commit history showing Ananth Iyer authoring auth module work",
    dueLabel: "Continuous, reviewed monthly",
    overdueLabel: null,
    status: "MET",
  },
  {
    id: "exp-15",
    commitmentId: "cm-19",
    expectedType: "GIT_COMMIT",
    expectedLabel: "Commit history showing Meenal Joshi authoring frontend work",
    dueLabel: "Continuous, reviewed monthly (last review 2026-09-01)",
    overdueLabel: "11 days overdue",
    status: "MISSING",
  },
  {
    id: "exp-16",
    commitmentId: "cm-20",
    expectedType: "SBOM",
    expectedLabel: "SBOM confirming all subprocessors hosted in India",
    dueLabel: "Before each production deploy",
    overdueLabel: null,
    status: "PENDING",
  },
];
