import type { GateEvent } from "@/types/deviation";

/**
 * ANUBANDH prototype addition — hand-authored gate checkpoint decisions for
 * project-1, across PASS / PASS_WITH_EVIDENCE / HOLD. ge-4 is already
 * overridden (see db/overrides.ts). See plan.md/update (1).md TASK 1.13.
 */
export const gateEvents: GateEvent[] = [
  {
    id: "ge-1",
    projectId: "project-1",
    nodeId: "node-1-foundation",
    checkpointLabel: "Foundation concrete pour gate",
    decision: "PASS",
    level: "L0",
    reasons: ["Aggregate sourced from approved vendor (Quarry Q-114)", "Cube tests on file"],
    valueAtRisk: 0,
    timeRemaining: "passed",
    at: "2025-08-01T09:00:00.000Z",
    overrideId: null,
  },
  {
    id: "ge-2",
    projectId: "project-1",
    nodeId: "node-1-wiring",
    checkpointLabel: "Traction power energization gate",
    decision: "PASS_WITH_EVIDENCE",
    level: "L2",
    reasons: ["Insulation certificate filed 2 days late but the test result passed"],
    valueAtRisk: 0,
    timeRemaining: "passed",
    at: "2025-09-10T00:00:00.000Z",
    overrideId: null,
  },
  {
    id: "ge-3",
    projectId: "project-1",
    nodeId: "node-1-structure",
    checkpointLabel: "Elevated structure concrete pour gate",
    decision: "HOLD",
    level: "L3",
    reasons: [
      "Seller GSTIN on the e-invoice does not match the approved vendor list",
      "E-way bill origin is 40km from the approved quarry",
      "Bank payment settled to the unapproved seller, not Quarry Q-114",
      "Feeds directly into the structural concrete pour scheduled today",
    ],
    valueAtRisk: 14_200_000,
    timeRemaining: "3h 49m",
    at: "2026-09-12T08:11:00.000Z",
    overrideId: null,
  },
  {
    id: "ge-4",
    projectId: "project-1",
    nodeId: "node-1-electrical",
    checkpointLabel: "Electrical panel access gate",
    decision: "HOLD",
    level: "L4",
    reasons: [
      "Gate credential belongs to a subcontractor with a REVOKED credential",
      "None of the 6 biometric check-ins match the ElectroWorks roster",
    ],
    valueAtRisk: 6_800_000,
    timeRemaining: "passed",
    at: "2026-09-11T07:20:00.000Z",
    overrideId: "ovr-1",
  },
  {
    id: "ge-5",
    projectId: "project-1",
    nodeId: "node-1-plumbing",
    checkpointLabel: "Drainage trench inspection gate",
    decision: "PASS",
    level: "L0",
    reasons: ["Progress photo on file", "No safety issues reported"],
    valueAtRisk: 0,
    timeRemaining: "passed",
    at: "2026-09-12T09:05:00.000Z",
    overrideId: null,
  },
  {
    id: "ge-6",
    projectId: "project-1",
    nodeId: "node-1-foundation",
    checkpointLabel: "Foundation aggregate gate — initial delivery",
    decision: "HOLD",
    level: "L3",
    reasons: ["Alternate quarry used for the first delivery batch, not yet on the approved vendor list"],
    valueAtRisk: 500_000,
    timeRemaining: "passed",
    at: "2025-07-15T09:00:00.000Z",
    overrideId: "ovr-2",
  },
  {
    id: "ge-7",
    projectId: "project-1",
    nodeId: "node-1-foundation",
    checkpointLabel: "Aggregate delivery diversion check",
    decision: "HOLD",
    level: "L3",
    reasons: [
      "Buyer GSTIN on the e-invoice belongs to a different site, not this project",
      "Consignment appears to have been diverted before reaching this project's gate",
    ],
    valueAtRisk: 890_000,
    timeRemaining: "5h 10m",
    at: "2026-09-12T10:00:00.000Z",
    overrideId: null,
  },

  // ---- ANUBANDH addition (TASK 9) — project-4 deploy checkpoint ----
  {
    id: "ge-8",
    projectId: "project-4",
    nodeId: "node-4-deploy",
    checkpointLabel: "Production deploy gate",
    decision: "HOLD",
    level: "L3",
    reasons: [
      "SBOM for release 4.3.0 lists a subprocessor with no India hosting region",
      "Data-residency commitment has zero tolerance for this",
    ],
    valueAtRisk: 9_500_000,
    timeRemaining: "5h 00m",
    at: "2026-09-11T22:10:00.000Z",
    overrideId: null,
  },
];
